list: $/branmuffin/googleconnect/models/configs/columns.yaml
modelClass: BranMuffin\GoogleConnect\Models\Configs
title: Configs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'branmuffin/googleconnect/configs/update/:id'
